# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/ucsdExtension/Fgpa1/final/final_uut/final_uut.srcs/sources_1/ip/FPGA_CLK/FPGA_CLK.xci
# IP: The module: 'FPGA_CLK' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/ucsdExtension/Fgpa1/final/final_uut/final_uut.srcs/sources_1/ip/FPGA_CLK/FPGA_CLK_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FPGA_CLK'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/ucsdExtension/Fgpa1/final/final_uut/final_uut.srcs/sources_1/ip/FPGA_CLK/FPGA_CLK.xdc
# XDC: The top module name and the constraint reference have the same name: 'FPGA_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/ucsdExtension/Fgpa1/final/final_uut/final_uut.srcs/sources_1/ip/FPGA_CLK/FPGA_CLK_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FPGA_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: G:/ucsdExtension/Fgpa1/final/final_uut/final_uut.srcs/sources_1/ip/FPGA_CLK/FPGA_CLK.xci
# IP: The module: 'FPGA_CLK' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/ucsdExtension/Fgpa1/final/final_uut/final_uut.srcs/sources_1/ip/FPGA_CLK/FPGA_CLK_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FPGA_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/ucsdExtension/Fgpa1/final/final_uut/final_uut.srcs/sources_1/ip/FPGA_CLK/FPGA_CLK.xdc
# XDC: The top module name and the constraint reference have the same name: 'FPGA_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/ucsdExtension/Fgpa1/final/final_uut/final_uut.srcs/sources_1/ip/FPGA_CLK/FPGA_CLK_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FPGA_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
